server:
  port: 8006
spring:
  application:
    name: news-consumer
  mvc:
    view:
      suffix: .html
    static-path-pattern: /static/**
  thymeleaf:
    prefix: /templates/
eureka:
  client:
    service-url:
      defaultZone: http://root:ok@localhost:7001/eureka/
  instance:
    instance-id: newsconsumer8004
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
news-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
